import { byId, type Dock } from "./dock";
export type Collection = {
  id: string;
  title: string;
  description: string;
  group: string;
  addedOn: string;
  apps: string[];
  rationale: string;
  credit?: string;
};
export const groups = [
  {
    id: "everyday",
    name: "Everyday Docks",
    shortName: "Everyday",
    description: "A few good essentials.",
  },
  {
    id: "design",
    name: "For the design desk",
    shortName: "Design",
    description: "From the first sketch to the handoff.",
  },
  {
    id: "photo-video",
    name: "Photo & video",
    shortName: "Photo & video",
    description: "Make room for the next edit.",
  },
  {
    id: "development",
    name: "Build & ship",
    shortName: "Development",
    description: "Tools for making software.",
  },
  {
    id: "research",
    name: "Read, write & research",
    shortName: "Research",
    description: "Follow an idea a little further.",
  },
  {
    id: "together",
    name: "Working together",
    shortName: "Together",
    description: "Keep the conversation close.",
  },
  {
    id: "music",
    name: "Listen & play",
    shortName: "Music",
    description: "What is playing while the rest happens.",
  },
  {
    id: "minimal",
    name: "Small Docks",
    shortName: "Minimal",
    description: "As little as you can get away with.",
  },
];
export const collections: Collection[] = [
  {
    id: "apple-essentials",
    title: "Apple essentials",
    description: "The familiar things, all in one place.",
    group: "everyday",
    addedOn: "2026-09-04",
    apps: ["finder","calendar","notes","mail","messages","music"],
    rationale: "A starting point for an ordinary day: files, plans, notes, messages, and something to listen to.",
  },
  {
    id: "less-but-enough",
    title: "Less, but enough",
    description: "Four icons. A little more breathing room.",
    group: "everyday",
    addedOn: "2026-09-04",
    apps: ["finder","notes","mail","calendar"],
    rationale: "Keep only the daily essentials in view. Add the apps your current project needs when you make this Dock your own.",
  },
  {
    id: "after-hours",
    title: "After hours",
    description: "Close the work tabs. Open something good.",
    group: "everyday",
    addedOn: "2026-09-04",
    apps: ["books","music","messages"],
    rationale: "A smaller evening Dock for reading, listening, and staying in touch.",
  },
  {
    id: "interface-workshop",
    title: "Interface workshop",
    description: "Sketch, prototype, and put it on the web.",
    group: "design",
    addedOn: "2026-09-04",
    apps: ["figma","paper","framer","arc","resurf"],
    rationale: "An interface-focused set that puts design tools beside a browser and a place to keep visual references.",
  },
  {
    id: "brand-studio",
    title: "Brand studio",
    description: "Type, color, images, and the bigger picture.",
    group: "design",
    addedOn: "2026-09-04",
    apps: ["illustrator","photoshop","figma","resurf"],
    rationale: "Move between vector work, image editing, layout, and the references that tie a visual identity together.",
  },
  {
    id: "design-handoff",
    title: "Design handoff",
    description: "Share the details that make the difference.",
    group: "design",
    addedOn: "2026-09-04",
    apps: ["figma","shotbase","notion","slack","mail"],
    rationale: "A collaborative design Dock for the moment a design needs context, a screenshot, and a conversation.",
  },
  {
    id: "photo-desk",
    title: "Photo desk",
    description: "From a first selection to the final image.",
    group: "photo-video",
    addedOn: "2026-09-04",
    apps: ["lightroom","photoshop","calendar","mail"],
    rationale: "Editing sits beside the practical work of planning shoots and delivering photographs.",
  },
  {
    id: "edit-suite",
    title: "Edit suite",
    description: "A focused home for moving images.",
    group: "photo-video",
    addedOn: "2026-09-04",
    apps: ["premiere","photoshop","music","notes"],
    rationale: "Keep the edit, supporting graphics, and notes within reach without filling every spot in the Dock.",
  },
  {
    id: "short-form-studio",
    title: "Short-form studio",
    description: "Small videos, considered from start to finish.",
    group: "photo-video",
    addedOn: "2026-09-04",
    apps: ["capcut","lightroom","notion","spotify"],
    rationale: "A compact set for assembling short videos, working on images, and keeping track of the next idea.",
  },
  {
    id: "native-workbench",
    title: "Native workbench",
    description: "An app idea, a project, and a place to start.",
    group: "development",
    addedOn: "2026-09-04",
    apps: ["xcode","github","notes"],
    rationale: "A deliberately small starting point for native app work, with code, repositories, and notes together.",
  },
  {
    id: "ship-a-website",
    title: "Ship a website",
    description: "From a blank canvas to a browser tab.",
    group: "development",
    addedOn: "2026-09-04",
    apps: ["figma","framer","github","arc","notion"],
    rationale: "Bring design, publishing, repositories, browser checks, and project notes into the same workspace.",
  },
  {
    id: "agent-workshop",
    title: "Agent workshop",
    description: "Code, compare, and keep a human in the loop.",
    group: "development",
    addedOn: "2026-09-04",
    apps: ["antigravity-ide","opencode","claude","github","notes"],
    rationale: "A place for trying assisted coding workflows while keeping project history and your own notes close.",
  },
  {
    id: "read-write-cite",
    title: "Read, write, cite",
    description: "For the long paper and the interesting footnote.",
    group: "research",
    addedOn: "2026-09-04",
    apps: ["zotero","books","notes","notion","resurf"],
    rationale: "A research-minded Dock that keeps reading, references, saved material, and writing in one view.",
  },
  {
    id: "research-trail",
    title: "Research trail",
    description: "Follow a question. Keep what you find.",
    group: "research",
    addedOn: "2026-09-04",
    apps: ["perplexity","chatgpt-atlas","resurf","zotero","notes"],
    rationale: "Explore sources in the browser, collect the useful ones, and keep notes alongside your reference library.",
  },
  {
    id: "quiet-writing",
    title: "Quiet writing",
    description: "An open note, a good book, a little music.",
    group: "research",
    addedOn: "2026-09-04",
    apps: ["notes","books","music"],
    rationale: "Three simple places to spend an unhurried writing session. Add your preferred editor when you customize it.",
  },
  {
    id: "team-day",
    title: "Team day",
    description: "The shared plans and everyday conversations.",
    group: "together",
    addedOn: "2026-09-04",
    apps: ["slack","calendar","mail","notion","figma"],
    rationale: "A workday set for shared projects, meetings, decisions, and the occasional design review.",
  },
  {
    id: "community-desk",
    title: "Community desk",
    description: "Stay in the loop without losing your place.",
    group: "together",
    addedOn: "2026-09-04",
    apps: ["discord","messages","calendar","notion","spotify"],
    rationale: "A casual collaboration Dock for community conversations, plans, shared notes, and background listening.",
  },
  {
    id: "capture-and-collect",
    title: "Capture & collect",
    description: "Save the thought before it disappears.",
    group: "together",
    addedOn: "2026-09-04",
    apps: ["aside","resurf","shotbase","notes","superwhisper"],
    rationale: "A browser, a reference library, screenshots, notes, and dictation for gathering the pieces of a new project.",
  },
  {
    id: "morning-desk",
    title: "Morning desk",
    description: "Open the day in a sensible order.",
    group: "everyday",
    addedOn: "2026-09-05",
    apps: ["calendar","mail","reminders","weather"],
    rationale: "Calendar, mail, and reminders sit beside the weather so the first look at the Dock is the day ahead.",
  },
  {
    id: "type-and-color",
    title: "Type & color",
    description: "Letters, palettes, and the next layout.",
    group: "design",
    addedOn: "2026-09-05",
    apps: ["font-book","affinity","illustrator","figma","digital-color-meter"],
    rationale: "Keep type, color sampling, and layout tools together when a visual system is the work.",
  },
  {
    id: "pixelmator-desk",
    title: "Pixelmator desk",
    description: "A lighter image editor, still close to Photos.",
    group: "photo-video",
    addedOn: "2026-09-05",
    apps: ["pixelmator-pro","photos","preview"],
    rationale: "Edit, compare, and file images without filling the Dock with every Creative Cloud icon.",
  },
  {
    id: "cursor-desk",
    title: "Cursor desk",
    description: "An editor, a terminal, and the repository.",
    group: "development",
    addedOn: "2026-09-05",
    apps: ["cursor","terminal","github","arc","notes"],
    rationale: "A software Dock that keeps the editor next to git, a browser, and a place for stray notes.",
  },
  {
    id: "obsidian-vault",
    title: "Obsidian vault",
    description: "Notes that connect, with books nearby.",
    group: "research",
    addedOn: "2026-09-05",
    apps: ["obsidian","zotero","safari","books","music"],
    rationale: "A writing-and-reference Dock for people who think in linked notes rather than a single document.",
  },
  {
    id: "spotify-desk",
    title: "Spotify desk",
    description: "A browser, a note, and something playing.",
    group: "music",
    addedOn: "2026-09-05",
    apps: ["spotify","safari","notes","messages"],
    rationale: "Listening stays in the Dock while you browse, jot, and answer the occasional message.",
  },
  {
    id: "errands",
    title: "Errands",
    description: "Lists, maps, and the next appointment.",
    group: "everyday",
    addedOn: "2026-09-06",
    apps: ["reminders","maps","mail","calendar","notes"],
    rationale: "A practical outing Dock: what to do, where to go, and how to follow up.",
  },
  {
    id: "freeform-board",
    title: "Freeform board",
    description: "A canvas, a sketch, and the photos you need.",
    group: "design",
    addedOn: "2026-09-06",
    apps: ["freeform","paper","notes","safari","photos"],
    rationale: "Spatial thinking with a sketching app, a browser, and the camera roll in easy reach.",
  },
  {
    id: "resolve-suite",
    title: "Resolve suite",
    description: "Color, cut, and a place for notes.",
    group: "photo-video",
    addedOn: "2026-09-06",
    apps: ["davinci-resolve","photos","music","notes"],
    rationale: "A finishing Dock for picture work that still leaves room for stills, music, and notes.",
  },
  {
    id: "xcode-and-sim",
    title: "Xcode desk",
    description: "The project, the terminal, a note.",
    group: "development",
    addedOn: "2026-09-06",
    apps: ["xcode","terminal","notes","safari"],
    rationale: "Native work with a terminal, a note, and documentation in the browser.",
  },
  {
    id: "craft-notes",
    title: "Craft notes",
    description: "A nicer document, a quieter desk.",
    group: "research",
    addedOn: "2026-09-06",
    apps: ["craft","safari","books","music","reminders"],
    rationale: "Documents, reading, and a reminder list for people who want the writing app to feel considered.",
  },
  {
    id: "three-icons",
    title: "Three icons",
    description: "Finder, Notes, Safari. That is the Dock.",
    group: "minimal",
    addedOn: "2026-09-06",
    apps: ["finder","notes","safari"],
    rationale: "A reminder that most days do not need a crowded row of tools.",
  },
  {
    id: "weekend-home",
    title: "Weekend home",
    description: "Photos, music, a show, a book.",
    group: "everyday",
    addedOn: "2026-09-07",
    apps: ["photos","music","tv","books","safari"],
    rationale: "An at-home Dock that trades mail and calendars for the things you actually open on Saturday.",
  },
  {
    id: "canva-quick",
    title: "Canva quick",
    description: "A layout before the meeting starts.",
    group: "design",
    addedOn: "2026-09-07",
    apps: ["canva","photos","safari","mail"],
    rationale: "Fast visual work with the photo library, a browser, and a way to send the result.",
  },
  {
    id: "screenshot-day",
    title: "Screenshot day",
    description: "Capture, crop, send.",
    group: "photo-video",
    addedOn: "2026-09-07",
    apps: ["screenshot","shotbase","preview","notes","messages"],
    rationale: "When the work is explaining a screen to someone else, keep capture and sharing beside each other.",
  },
  {
    id: "jetbrains",
    title: "IntelliJ desk",
    description: "A heavier IDE, still a small Dock.",
    group: "development",
    addedOn: "2026-09-07",
    apps: ["intellij-idea","terminal","github","slack","arc"],
    rationale: "JVM or Android work with chat and a browser close, without duplicating every utility.",
  },
  {
    id: "google-docs-day",
    title: "Docs day",
    description: "The browser suite, used on purpose.",
    group: "research",
    addedOn: "2026-09-07",
    apps: ["google-docs","google-drive","safari","calendar","mail"],
    rationale: "A writing day that lives in Google’s apps, with calendar and mail for the surrounding logistics.",
  },
  {
    id: "student-core",
    title: "Student core",
    description: "Notes, calendar, books, a paper.",
    group: "minimal",
    addedOn: "2026-09-07",
    apps: ["notes","calendar","safari","books","pages"],
    rationale: "A school Dock that covers reading, writing, and when the next thing is due.",
  },
  {
    id: "family-mac",
    title: "Family Mac",
    description: "Photos, messages, a FaceTime, the calendar.",
    group: "everyday",
    addedOn: "2026-09-08",
    apps: ["photos","messages","facetime","calendar","tv"],
    rationale: "A shared computer Dock: the people, the pictures, and something to watch together.",
  },
  {
    id: "icon-desk",
    title: "Icon desk",
    description: "Pixels at 1×, with Preview as a second pair of eyes.",
    group: "design",
    addedOn: "2026-09-08",
    apps: ["affinity","preview","font-book","figma"],
    rationale: "Icon and small-graphic work needs an editor, a preview, type, and the file that will ship.",
  },
  {
    id: "iphone-photos",
    title: "iPhone photos",
    description: "Import, sort, send a proof.",
    group: "photo-video",
    addedOn: "2026-09-08",
    apps: ["photos","image-capture","preview","mail"],
    rationale: "A Dock for getting pictures off a phone and out to someone waiting on them.",
  },
  {
    id: "terminal-first",
    title: "Terminal first",
    description: "The prompt, then the editor.",
    group: "development",
    addedOn: "2026-09-08",
    apps: ["terminal","cursor","github","notes","music"],
    rationale: "For people who open a shell before they open a file, with music for the long compile.",
  },
  {
    id: "pages-writer",
    title: "Pages writer",
    description: "A Mac document, a dictionary, a book.",
    group: "research",
    addedOn: "2026-09-08",
    apps: ["pages","books","notes","music","dictionary"],
    rationale: "Long-form writing in Pages with reference books and a dictionary in the same row.",
  },
  {
    id: "apple-music",
    title: "Apple Music",
    description: "The library you already paid for.",
    group: "music",
    addedOn: "2026-09-08",
    apps: ["music","podcasts","notes"],
    rationale: "Music and podcasts as first-class apps, with a note for the occasional track list.",
  },
  {
    id: "health-day",
    title: "Health day",
    description: "Clock, reminders, a journal.",
    group: "everyday",
    addedOn: "2026-09-09",
    apps: ["clock","reminders","journal","music","weather"],
    rationale: "A gentler Dock for days that are more about pacing than producing.",
  },
  {
    id: "framer-ship",
    title: "Framer ship",
    description: "Design it, publish it, check it.",
    group: "design",
    addedOn: "2026-09-09",
    apps: ["framer","figma","safari","github","notion"],
    rationale: "A site that starts in Figma or Framer still needs a browser, a repo, and project notes.",
  },
  {
    id: "video-compress",
    title: "Convert & send",
    description: "Downie, Permute, QuickTime.",
    group: "photo-video",
    addedOn: "2026-09-09",
    apps: ["downie","permute","quicktime-player","notes"],
    rationale: "A utility Dock for getting a video off the web, into the right format, and onto disk.",
  },
  {
    id: "t3-nightly",
    title: "T3 nightly",
    description: "An experimental editor beside git.",
    group: "development",
    addedOn: "2026-09-09",
    apps: ["t3-code-nightly","terminal","github","arc","notion"],
    rationale: "Trying a newer coding tool without abandoning the repository, browser, and notes.",
  },
  {
    id: "journal-first",
    title: "Journal first",
    description: "Private writing before the inbox.",
    group: "research",
    addedOn: "2026-09-09",
    apps: ["journal","notes","books","music"],
    rationale: "Start in Journal, keep Notes for the rest, and leave mail out of the row.",
  },
  {
    id: "writer-only",
    title: "Writer only",
    description: "Notes and Books. Nothing else.",
    group: "minimal",
    addedOn: "2026-09-09",
    apps: ["notes","books"],
    rationale: "Two apps. If the session needs more, add them when you make it yours.",
  },
  {
    id: "default-mac",
    title: "Classic Mac",
    description: "The Dock many people already have.",
    group: "everyday",
    addedOn: "2026-09-10",
    apps: ["finder","safari","mail","messages","photos","music"],
    rationale: "Finder, Safari, Mail, Messages, Photos, Music — the familiar Apple set, named so you can fork it.",
  },
  {
    id: "color-lab",
    title: "Color lab",
    description: "Meters, profiles, and an editor.",
    group: "design",
    addedOn: "2026-09-10",
    apps: ["digital-color-meter","colorsync-utility","affinity","photoshop","notes"],
    rationale: "When color has to be right, keep the meters next to the editors that will use the number.",
  },
  {
    id: "photo-booth-fun",
    title: "Photo Booth",
    description: "A silly camera, then Messages.",
    group: "photo-video",
    addedOn: "2026-09-10",
    apps: ["photo-booth","photos","messages","preview"],
    rationale: "Not every photo Dock is a studio. This one is for a quick picture and sending it along.",
  },
  {
    id: "zcode-lab",
    title: "ZCode lab",
    description: "Another editor, the same git habit.",
    group: "development",
    addedOn: "2026-09-10",
    apps: ["zcode","terminal","github","notes"],
    rationale: "A compact coding Dock for trying ZCode without extra chat or browsers in the way.",
  },
  {
    id: "markdown-lab",
    title: "Markdown lab",
    description: "Preview, TextEdit, a vault.",
    group: "research",
    addedOn: "2026-09-10",
    apps: ["markdown-preview","textedit","obsidian","github"],
    rationale: "Plain-text writing with a preview, a vault, and the repo that will publish it.",
  },
  {
    id: "podcast-morning",
    title: "Podcast morning",
    description: "Walk, listen, jot one line.",
    group: "music",
    addedOn: "2026-09-10",
    apps: ["podcasts","safari","notes","calendar"],
    rationale: "A morning Dock for an episode, a follow-up link, and whatever the calendar says next.",
  },
  {
    id: "passwords-first",
    title: "Passwords first",
    description: "The keychain, then the browser.",
    group: "everyday",
    addedOn: "2026-09-11",
    apps: ["passwords","safari","mail","notes"],
    rationale: "Sign-in days go better when Passwords is in the Dock instead of buried in Settings.",
  },
  {
    id: "presentation-deck",
    title: "Presentation deck",
    description: "Keynote, Figma, the pictures.",
    group: "design",
    addedOn: "2026-09-11",
    apps: ["keynote","figma","photos","notes"],
    rationale: "A talk is slides, source layouts, images, and the outline you promised yourself.",
  },
  {
    id: "premiere-cut",
    title: "Premiere cut",
    description: "The NLE, Photoshop, Shotbase.",
    group: "photo-video",
    addedOn: "2026-09-11",
    apps: ["premiere","photoshop","music","shotbase"],
    rationale: "An Adobe-leaning edit Dock with stills, captures, and music in the same row.",
  },
  {
    id: "bitrig-build",
    title: "Bitrig build",
    description: "A smaller tool, a real project.",
    group: "development",
    addedOn: "2026-09-11",
    apps: ["bitrig","terminal","github","notes"],
    rationale: "Keep Bitrig beside the terminal and the repo so an experiment can still ship.",
  },
  {
    id: "acrobat-paper",
    title: "Acrobat paper",
    description: "PDFs, citations, a highlighter in spirit.",
    group: "research",
    addedOn: "2026-09-11",
    apps: ["acrobat","zotero","preview","notes","safari"],
    rationale: "Reading papers means a PDF app, a library, and a place to keep the sentence you might quote.",
  },
  {
    id: "one-browser",
    title: "One browser",
    description: "Safari, Notes, Mail.",
    group: "minimal",
    addedOn: "2026-09-11",
    apps: ["safari","notes","mail"],
    rationale: "Three icons for a computer that is mostly a window onto the web and a mailbox.",
  },
  {
    id: "commuter",
    title: "Commuter",
    description: "Maps, a podcast, the next message.",
    group: "everyday",
    addedOn: "2026-09-12",
    apps: ["maps","podcasts","messages","music","calendar"],
    rationale: "A leaving-the-house Dock: where you are going, what you will listen to, who might ping.",
  },
  {
    id: "slack-hq",
    title: "Slack HQ",
    description: "The workplace lives in one row.",
    group: "together",
    addedOn: "2026-09-12",
    apps: ["slack","calendar","mail","notion","safari"],
    rationale: "Chat, calendar, mail, and the doc that will be pasted into Slack in five minutes.",
  },
  {
    id: "claude-pair",
    title: "Claude pair",
    description: "The model, the editor, the repo.",
    group: "development",
    addedOn: "2026-09-12",
    apps: ["claude","cursor","github","notes","safari"],
    rationale: "Assisted coding with a dedicated Claude app beside the editor you still have to own.",
  },
  {
    id: "facetime-friday",
    title: "FaceTime Friday",
    description: "Calls, messages, a calendar.",
    group: "together",
    addedOn: "2026-09-12",
    apps: ["facetime","messages","calendar","photos","music"],
    rationale: "A people-first Dock for catching up, with photos if someone says “wait, I’ll show you.”",
  },
  {
    id: "midi-room",
    title: "MIDI room",
    description: "Audio MIDI Setup and the library.",
    group: "music",
    addedOn: "2026-09-12",
    apps: ["audio-midi-setup","music","voice-memos"],
    rationale: "A small audio Dock for checking devices, recording a memo, and filing the result.",
  },
  {
    id: "exam-week",
    title: "Exam week",
    description: "Calendar, reminders, calculator.",
    group: "minimal",
    addedOn: "2026-09-12",
    apps: ["notes","calendar","reminders","books","calculator"],
    rationale: "Study logistics: what is due, what to remember, and a calculator that is not a phone.",
  },
  {
    id: "chatgpt-desk",
    title: "ChatGPT desk",
    description: "A chat, a browser, a note.",
    group: "research",
    addedOn: "2026-09-13",
    apps: ["chatgpt","safari","notes","notion"],
    rationale: "Use a chat app as a thinking partner without letting it replace the browser or your own notes.",
  },
  {
    id: "discord-studio",
    title: "Discord studio",
    description: "Voice, Spotify, a project doc.",
    group: "together",
    addedOn: "2026-09-13",
    apps: ["discord","spotify","notion","safari"],
    rationale: "Community calls with music, a shared doc, and a browser for whatever you promised to send.",
  },
  {
    id: "opencode-solo",
    title: "OpenCode solo",
    description: "The agent, Cursor, git.",
    group: "development",
    addedOn: "2026-09-13",
    apps: ["opencode","cursor","github","notes","music"],
    rationale: "Two coding surfaces and a repo, with music for the stretches where you are only reading diffs.",
  },
  {
    id: "phone-desk",
    title: "Phone desk",
    description: "The Mac as a handset.",
    group: "together",
    addedOn: "2026-09-13",
    apps: ["phone","messages","facetime","calendar","notes"],
    rationale: "Calls and texts as Dock apps, with the calendar so you know why the phone is ringing.",
  },
  {
    id: "tv-evening",
    title: "TV evening",
    description: "The living-room Mac.",
    group: "music",
    addedOn: "2026-09-13",
    apps: ["tv","music","podcasts","photos"],
    rationale: "Watch, listen, and flip through pictures. Work apps can wait until morning.",
  },
  {
    id: "calculator-lab",
    title: "Numbers lab",
    description: "Calculator, Grapher, a spreadsheet.",
    group: "minimal",
    addedOn: "2026-09-13",
    apps: ["calculator","grapher","notes","preview","numbers"],
    rationale: "A small quantitative Dock for homework, a graph, and the spreadsheet that holds the table.",
  },
  {
    id: "gemini-search",
    title: "Gemini & Perplexity",
    description: "Two research chats, then Notes.",
    group: "research",
    addedOn: "2026-09-14",
    apps: ["gemini","perplexity","notes","safari"],
    rationale: "Compare answers, keep the useful sentence, and still open the original page.",
  },
  {
    id: "screen-share",
    title: "Screen share",
    description: "Show the work, take the note.",
    group: "together",
    addedOn: "2026-09-14",
    apps: ["screen-sharing","slack","safari","notes","calendar"],
    rationale: "A support or pairing Dock: the share, the chat, and the calendar block you are in.",
  },
  {
    id: "voice-to-text",
    title: "Voice to text",
    description: "Speak it, then file it.",
    group: "research",
    addedOn: "2026-09-14",
    apps: ["superwhisper","notes","safari","mail"],
    rationale: "Dictation first, then a note, a browser, and mail for the thing you just promised.",
  },
  {
    id: "local-ai",
    title: "Local-ish AI",
    description: "A few chat apps, one notes file.",
    group: "development",
    addedOn: "2026-09-14",
    apps: ["grok-bot","claude","chatgpt","notes","safari"],
    rationale: "Keep more than one assistant around, and a note so their answers do not vanish.",
  },
  {
    id: "keynote-rehearsal",
    title: "Keynote rehearsal",
    description: "Slides, notes, a timer.",
    group: "design",
    addedOn: "2026-09-15",
    apps: ["keynote","notes","clock","preview","safari"],
    rationale: "Practice the deck with a clock in the Dock so you can see the time without a notification.",
  },
  {
    id: "lightroom-select",
    title: "Lightroom select",
    description: "Culling, then Calendar for the deadline.",
    group: "photo-video",
    addedOn: "2026-09-15",
    apps: ["lightroom","photos","calendar","notes"],
    rationale: "A selection-day Dock: the catalog, the camera roll, and when the gallery is due.",
  },
  {
    id: "maps-weekend",
    title: "Maps weekend",
    description: "Where to go, what the weather is.",
    group: "everyday",
    addedOn: "2026-09-16",
    apps: ["maps","weather","calendar","photos","safari"],
    rationale: "A wandering Dock: maps, weather, the plan, and the camera roll from last time.",
  },
  {
    id: "affinity-only",
    title: "Affinity only",
    description: "One design suite, Preview, Photos.",
    group: "design",
    addedOn: "2026-09-16",
    apps: ["affinity","preview","font-book","photos"],
    rationale: "Stay inside Affinity for the day and keep type and photos at the edge of the Dock.",
  },
  {
    id: "quicktime-review",
    title: "QuickTime review",
    description: "Watch the export, then send it.",
    group: "photo-video",
    addedOn: "2026-09-17",
    apps: ["quicktime-player","mail","notes","messages"],
    rationale: "A review Dock for watching a file all the way through before it leaves the machine.",
  },
];
export const collectionById = new Map(
  collections.map((item) => [item.id, item]),
);
export function collectionDock(item: Collection): Dock {
  return { v: 2, n: item.title, t: item.description, a: [...item.apps] };
}
export function matchesCollection(item: Collection, query: string) {
  const text = [
    item.title,
    item.description,
    groups.find((g) => g.id === item.group)?.name,
    ...item.apps.map((id) => byId.get(id)?.name ?? ""),
  ]
    .join(" ")
    .toLocaleLowerCase();
  return text.includes(query.trim().toLocaleLowerCase());
}
export function latestCollections() {
  return [...collections].sort(
    (a, b) =>
      b.addedOn.localeCompare(a.addedOn) ||
      collections.indexOf(a) - collections.indexOf(b),
  );
}
export function formatDate(date: string) {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(`${date}T12:00:00Z`));
}
